services:
  # The web server (Nginx) to serve the Magento application
  nginx:
    image: nginx:stable-alpine
    container_name: magento_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - magento_network

  # The PHP-FPM service for processing Magento's PHP code
  php:
    image: php:8.2-fpm-alpine
    container_name: magento_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      # Coolify will provide the actual values for these variables at runtime
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
      - MAGENTO_ADMIN_USER=${MAGENTO_ADMIN_USER}
      - MAGENTO_ADMIN_PASSWORD=${MAGENTO_ADMIN_PASSWORD}
      # Add other Magento-specific variables here
    networks:
      - magento_network

  # The MySQL database
  mysql:
    image: mysql:8.0
    container_name: magento_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - magento_network

  # OpenSearch service for catalog search
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: magento_opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Open@search12!3
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - magento_network

volumes:
  mysql_data:
  opensearch_data:

networks:
  magento_network:
    driver: bridge